import React from "react"
import { View, Text, ScrollView } from "react-native"
import Colors from "../../Constant/Color"
import CustomHeader from "../../Components/CustomHeader"
function PrivacyPolicy() {
    return (
        <View style={{ flex: 1, backgroundColor: Colors.white }} >


            <View style={{ marginTop: 10 }} >
                <CustomHeader

                    text={"Privacy Policy"}
                    iconname={"arrow-back-outline"}
                    color={Colors.black}
                    onPress={() => navigation.goBack()}


                />

            </View>
            <ScrollView >
                <Text style={{ fontSize: 18, fontFamily: "Poppins-Medium", color: Colors.black, marginHorizontal: 20, marginTop: 10 }} >
                    THIS CONTRACT CONTAINS AN ARBITRATION PROVISION WHICH MAY BE ENFORCED BY THE PARTIES. TAKE THE TIME AND SEEK ANY ASSISTANCE NEEDED TO COMPREHEND THE CONSEQUENCES OF ENTERING INTO THIS AGREEMENT.
                    1. CONTRACTUAL RELATIONSHIP
                    1.1 Agreement. This Agreement (“Agreement”) is made and entered into by and between you (“Customer” or “User”) and XOX Rides Inc. and or  (dba “Poochie app”)  (“Poochie” or “Company”) each of whom shall be referred to as a “Party” and collectively referred to as the “Parties’. The terms of this Agreement (“Terms”) govern your access or use of applications, websites, content, products, and services (individually and collectively “Services”) made available by Poochie and its parents, subsidiaries, representatives, affiliates, officers and directors. Please read these Terms carefully as they constitute a legal agreement between you and Poochie.
                    1.2 Summary Termination. By accessing or using the Services, you confirm your agreement to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Services. This Agreement expressly supersedes prior agreements or arrangements with you. Poochie may immediately terminate this Agreement or any Services with respect to you, or generally cease offering or deny access to the Services or any portion thereof, at any time for any reason.
                    1.3 Supplement Terms. Supplemental terms may apply to certain Services, such as policies for a particular event, program, activity or promotion, and such supplemental terms will be disclosed to you in separate disclosures or in connection with the applicable Service(s). Supplemental terms are in addition to, and shall be deemed a part of, this Agreement for the purposes of the applicable Service(s). Supplemental terms shall prevail over these Terms in the event of a conflict with respect to the applicable Services.
                    1.4 Poochie Amendments. Poochie may amend this Agreement from time to time. If Poochie amends the Agreement you will be notified by a message sent to the email address you provide in your contact information. Amendments will be effective upon posting of such updated Terms on the Poochie website. Your use of the Poochie Platform or Services after notification confirms your consent to be bound by the Agreement as amended. For Services used by you prior to the effective date of the amendment you will continue to be bound by the provisions of these Terms as of the date you first agreed to the Terms (or to any subsequent changes to these Terms).
                    2. DESCRIPTION OF SERVICES
                    2.1 Brokerage Service. Poochie provides an online marketplace connection using web-based technology that connects customers, contract drivers (“Contractors”) and pet services businesses (“Poochie Platform”). Poochie software permits registered users to request transportation for pets from Contractors. Poochie software notifies Contractors that a ride opportunity is available and the Poochie software facilitates the logistics and payment of the rides. XoX Rides Inc.and or  dba  Poochie or Poochie app is a technology-based services broker. The Contractor is a Pet Services Business.
                    YOU ACKNOWLEDGE THAT YOUR ABILITY TO SCHEDULE TRANSPORTATION FOR YOUR PET THROUGH THE USE OF POOCHIE DOES NOT ESTABLISH POOCIE AS A PROVIDER OF TRANSPORTATION, LOGISTICS OR DELIVERY SERVICES OR AS A TRANSPORTATION CARRIER.
                    2.2 License. Subject to your compliance with these Terms, Poochie grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to: (i) access and use the web-technology on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by Poochie.
                    2.3 Restrictions.
                    2.3.1 You may not remove any copyright, trademark or other proprietary notices from any portion of the Services.
                    2.3.2 You may not reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by Poochie.
                    2.3.3 You may not decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law.
                    2.3.4 You may not link to, mirror or frame any portion of the Services, cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services, or unduly burden or hinder the operation and/or functionality of any aspect of the Services.
                    2.3.5 You may not attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.
                    2.4. Third-Party Services and Content. The Services will be made available or accessed in connection with pet service businesses or third-party services that Poochie does not control. You acknowledge that different terms of use and privacy policies will apply to your use of such third-party services and content. Poochie does not endorse such third-party services and content; and, in no event shall Poochie be responsible or liable for any products or services of such third-party providers. Additionally, Apple Inc., Google, Inc., Microsoft Corporation or BlackBerry Limited will be a third-party beneficiary to this contract if you access the Services using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively. These third-party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third-party beneficiary’s terms of service.
                    2.5 Ownership. The Services and all rights therein are and shall remain Poochie property. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner Poochie company names, logos, product and service names, trademarks or services marks.
                    3. ACCESS AND USE OF THE SERVICES
                    3.1 User Accounts. In order to use most aspects of the Services, you must register for and maintain an active personal user Services account (“Account”). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account, unless a specific Service permits otherwise. Account registration requires you to submit to Poochie certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method supported by Poochie. You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, will result in your inability to access or use the Services. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. You may only possess one Account.
                    3.2 User Requirements and Conduct. The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to schedule pet transportation. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when accessing or using the Services, and you may only access or use the Services for lawful purposes (e.g., no transport of unlawful or hazardous materials). You may not in your access or use of the Services cause nuisance, annoyance, inconvenience, or property damage. In certain instances you will be asked to provide proof of identity or other method of identity verification to access or use the Services; and you will be denied access to or use of the Services if you refuse to provide proof of identity or other method of identity verification.
                    3.3 Text Messaging and Telephone Calls. You agree that Poochie may contact you by telephone or text messages (including by an automatic telephone dialing system) at any of the phone numbers provided by you or on your behalf in connection with a Poochie account, including for marketing purposes. You understand that you are not required to provide this consent as a condition of purchasing any property, goods or services. You also understand that you may opt out of receiving text messages from Poochie at any time, by contacting hello@poochieapp.com. If you do not choose to opt out, Poochie may contact you as outlined in its Privacy Statement.
                    3.4 User Provided Content. Poochie may, in Poochie’s sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to Poochie through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions (“User Content”). Any User Content provided by you remains your property. However, by providing User Content to Poochie, you grant Poochie a worldwide, perpetual, irrevocable, transferable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and Poochie’s business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.
                    3.4.1 You represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant Poochie  the license to the User Content as set forth above; and (ii) neither the User Content, nor your submission, uploading, publishing or otherwise making available of such User Content, nor Poochie’s use of the User Content as permitted herein will infringe, misappropriate or violate a third-party’s intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.
                    3.4.2 You agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by Poochie in its sole discretion, whether or not such material may be protected by law. Poochie may, but shall not be obligated to, review, monitor, or remove User Content, at Poochie’s sole discretion and at any time and for any reason, without notice to you.
                    3.5 Network Access and Devices. You are responsible for obtaining the data network access necessary to use the Services. Your mobile network’s data and messaging rates and fees may apply if you access or use the Services from your device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. Poochie does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.
                    4. PAYMENT
                    4.1 Amount. The use of the Services will result in charges to you for the services you receive (“Charges”). Poochie will receive and/or enable your payment of the applicable Charges for services obtained through your use of the Services. Charges will be inclusive of applicable taxes where required by law. Charges will include other applicable fees, tolls, and/or surcharges including booking fees, municipal tolls, airport surcharges or processing fees.
                    4.2 How Made. All Charges and payments will be enabled by Poochie, after which you will receive a receipt by email. If your Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that Poochie may use a secondary payment method in your Account, if available. Charges you pay are final and non-refundable.
                    4.3 Adjustments. As between you and Poochie, Poochie reserves the right to establish, remove, refund and/or revise Charges for the use of the Services at any time in Poochie’s sole discretion. Further, you acknowledge and agree that Charges applicable in certain geographical areas may increase substantially during times of high demand. Poochie will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof.
                    4.1 Special Deals. Poochie may from time to time provide certain users with promotional offers and discounts that will result in different amounts charged for the same or similar services through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you.
                    4.3 Service Cancellation. You may elect to cancel your scheduled Services up to 24 hours prior to the commencement of such Services, after which case you will be charged a cancellation fee of $15.00.
                    4.4. Feedback. After you have received Services or goods obtained through the Services, you will have the opportunity via email to rate your experience and leave additional feedback.
                    4.5 Application of Payments. Poochie may use the proceeds of any Charges for any purpose, subject to any payment obligations it has to Contractors as a broker.
                    4.6 Tips. Poochie does not designate any portion of your payment as a tip or gratuity to Contractors. You understand and agree that, while you are free to provide additional payment as a gratuity to Contractors who provide you pet transportation services, you are under no obligation to do so. Gratuities are voluntary.
                    4.7 Repair, Cleaning or Lost and Found Fees. You shall be responsible for the cost of repair for damage to, or necessary cleaning of Contractor vehicles and property resulting from use of pet transportation services under your Account in excess of normal “wear and tear” (“Repair or Cleaning”). In the event that a Repair or Cleaning request from the Contractor is verified by Poochie, Poochie will Charge your Account for the reasonable cost of such Repair or Cleaning using your payment method designated in your Account.
                    5. USER RESPONSIBILITIES
                    5.1 Your Pet. You hereby represent, covenant and warrant that with regard to pet(s) for which you request transportation services:
                    (a) you own the pet;
                    (b) the pet is free from fleas, ticks, other pests, and communicable disease (e.g. mange);
                    (c) you have divulged all material information about your pet(s), including pre-existing veterinary conditions, bite history, and behavioral issues that may be relevant or impact transportation services.
                    (d) the pet is not aggressive;
                    (e) you carry liability insurance that covers injuries and damages caused by your pet(s);
                    (f) the pet(s) is fully vaccinated and licensed as required by local laws;
                    (g) you shall provide accurate information about yourself and your pet(s).
                    5.2 Pet Damages. You are fully responsible for the actions of your pet(s). You are liable for any and all claims, costs, proceedings, demands, losses, damages, and expenses (including, without limitation, reasonable attorney’s fees and legal costs) or any kind or nature, arising from or relating to, the behavior of your pet(s), including without limitations, claims by third parties (including Contractors) for damages, loss or injuries resulting from bites or attacks on such third parties by your pet(s).
                    5.3 Contractor Discretion. Contractors have the sole and absolute discretion to reject or refuse any pet transportation services that you may request, even at the point of pickup, when:
                    (a) the physical condition or temperament of the pet prevents timely delivery, prevents safe transportation, or endangers the security of the pet;
                    (b) you vary the instructions and parameters of the desired service from that contained in your accepted order for pet transportation services (e.g. more than one pet, different pet, different time or place of delivery);
                    (c) transportation would be unlawful.
                    5.4 Veterinary Care in Transit.
                    (a) You Are Reached. If a Contractor or Poochie reaches you with a request to authorize veterinary care for your pet and you refuse, you are solely responsible for the consequences to your Pet(s).
                    (b) You Are Not Reached. If you cannot be reached to authorize care, and your pet needs immediate veterinary care in the estimation and discretion of Poochie or the Contractor, you hereby authorize the Contractor and/or Poochie to obtain and authorize veterinary care for your pet. You are solely responsible for the costs of any such veterinary treatment for your pet(s); and, you consent to and authorize Poochie to charge any of your payment methods for such costs.
                    (c) No Liability to Poochie or Contractor. Whether or not you are reached, you waive, release and promise never to assert any claims or causes of action arising from seeking veterinary care or failure to seek such care against Poochie and Contractor, and their predecessors, successors or past or present subsidiaries, stockholders, directors, officers, employees, consultants, attorneys, agents, or assigns with respect to any matter, including without limitation any claims of negligence, emotional distress, fraud, breach of contract, or breach of the covenant of good faith and fair dealing.
                    6. INDEMNITY DISCLAIMERS: LIMITATION OF LIABILITY
                    6.1 INDEMNITY – IT IS THE EXPRESS INTENT OF THE PARTIES TO PROVIDE FOR INDEMNIFICATION BY THE USER AND TO CONFORM TO THE PROVISIONS OF THE EXCEPTIONS TO ANY GENERAL PROHIBITION ON INDEMNITY CLAUSES CONTAINED IN THE APPLICABLE LAW OF THIS AGREEMENT. YOU AGREE TO INDEMNIFY AND HOLD POOCHIE AND ITS AFFILIATES AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FROM ANY AND ALL CLAIMS, DEMANDS, LOSSES, LIABILITIES, AND EXPENSES (INCLUDING ATTORNEYS’ FEES), ARISING OUT OF OR IN CONNECTION WITH: (I) YOUR USE OF THE SERVICES OR SERVICES OR GOODS OBTAINED THROUGH YOUR USE OF THE SERVICES; (II) YOUR BREACH OR VIOLATION OF ANY OF THESE TERMS; (III) POOCHIE’S USE OF YOUR USER CONTENT; OR (IV) YOUR VIOLATION OF THE RIGHTS OF ANY THIRD-PARTY, INCLUDING CONTRACTORS.
                    6.2 DISCLAIMER. THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” POOCHIE DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, POOCHIE MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, OR AVAILABILITY OF THE SERVICES OR ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. POOCHIE DOES NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF CONTRACTORS OR OTHER THIRD-PARTY PROVIDERS. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION THEREWITH, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW.
                    6.3 LIMITATION OF LIABILITY.
                    6.3.1 Poochie shall not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages, including lost profits, lost data, personal injury, or property damage related to, in connection with, or otherwise resulting from any use of the Services, regardless of the negligence (either active, affirmative, sole, or concurrent) of Poochie, even if Poochie has been advised of the possibility of such damages.
                    6.3.2 Poochie shall not be liable for any damages, liability or losses arising out of: (i) your use of or reliance on the Services or your inability to access or use the Services; or (ii) any transaction or relationship between you and any third-party provider, even if Poochie has been advised of the possibility of such damages. Poochie shall not be liable for delay or failure in performance resulting from causes beyond Poochie’s reasonable control. You acknowledge that third-party providers providing transportation services requested through some request products may offer ridesharing or peer-to-peer transportation services and may not be professionally licensed or permitted.
                    6.3.3 The Services may be used by you to request and schedule pet transportation services with contractors and other third-party providers, but you agree that Poochie has no responsibility or liability to you related to any transportation, goods or logistics services provided to you by contractor or other third-party providers other than as expressly set forth in these terms.
                    6.3.4 The limitations and disclaimer in this section 5 do not purport to limit liability or alter your rights as a consumer that cannot be excluded under applicable law. Because some states or jurisdictions do not allow the exclusion of or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, Poochie’s liability shall be limited to the extent permitted by law. This provision shall have no effect on the choice of law provision set forth below.
                    7. MUTUAL ARBITRATION PROVISION
                    7.1 Arbitration Governs All Disputes. User and Poochie mutually agree to this Mutual Arbitration Provision, which is governed by the Federal Arbitration Act (9 U.S.C. §§ 1-16) (“FAA”) and shall apply to any and all disputes arising out of or relating to this Agreement including without limitation harassment, discrimination or retaliation claims. The Parties expressly agree that this Agreement shall be governed by the FAA even in the event User and/or Poochie are otherwise exempted from the FAA. Any disputes in this regard shall be resolved exclusively by an arbitrator.
                    7.2 Class Arbitration Prohibited and Waived. User and Poochie mutually agree that by entering into this Agreement to arbitrate, both waive their right to have any dispute or Claim brought, heard or arbitrated as, or to participate in, a class action, collective action and/or representative action—including but not limited to actions brought pursuant to the Private Attorney General Act (“PAGA”), California Labor Code section 2699 et seq., and any request seeking a public injunction—and an arbitrator shall not have any authority to hear or arbitrate any class, collective or representative action, or to award relief to anyone but the individual in arbitration (“Arbitration Class Action Waiver”).
                    7.3 Initiation of Arbitration. If either User or Poochie wishes to initiate arbitration, the initiating Party must notify the other Party in writing via certified mail, return receipt requested, or hand delivery within the applicable statute of limitations period. This demand for arbitration must include (1) the name and address of the Party seeking arbitration, (2) a statement of the legal and factual basis of the claim, and (3) a description of the remedy sought and (4) the amount in controversy. Any demand for arbitration by User must be delivered to XOX Rides Inc, attention CEO 350 Salem st unit 201 Glendale Ca. 91203.
                    7.4 Arbitration Tribunal and Rules. Any arbitration shall be submitted to the International Institute for Conflict Prevention & Resolution (CPR), and governed by the CPR Administered Arbitration Rules and, when applicable, the CPR Employment-Related Mass-Claims Protocol (together, the “CPR Rules”) of the International Institute for Conflict Prevention & Resolution, except as follows:
                    7.4.1 The arbitration shall be heard by one arbitrator (the “Arbitrator”) selected in accordance with the CPR Rules. The Arbitrator shall be an attorney with experience in the law underlying the dispute.
                    7.4.2 The arbitration shall take place in Los Angeles County, Ca.
                    7.4.3 The CPR fee schedule will apply. The cost of the arbitration shall be borne equally by the Parties, except that each Party shall bear its own costs of preparation, counsel and presentation. A prevailing Party shall be entitled to an award of reasonable attorney’s fees and costs made by the Arbitrator and as a part of the arbitration award.
                    7.4.4 The Arbitrator may issue orders (including subpoenas to third parties) allowing the Parties to conduct discovery sufficient to allow each Party to prepare that Party’s claims and/or defenses, taking into consideration that arbitration is designed to be a speedy and efficient method for resolving disputes.
                    7.4.5 The Arbitrator shall be able to award any and all relief of an equitable nature, including but not limited to such relief as a temporary restraining order, a temporary and/or a permanent injunction, and shall also be able to award damages, with or without an accounting and costs The Arbitrator may issue orders to protect the confidentiality of proprietary information, trade secrets, or other sensitive information.
                    7.4.6. The Arbitrator may hear motions to dismiss and/or motions for summary judgment and will apply the standards of the Federal Rules of Civil Procedure governing such motions.
                    7.4.7. The Arbitrator’s decision or award shall be in writing with findings of fact and conclusions of law.
                    7.4.8. Subject to the discretion of the Arbitrator or agreement of the Parties, any person having a direct interest in the arbitration may attend the arbitration hearing. The Arbitrator may exclude any non-party from any part of the hearing.
                    7.4.9. Either User or Poochie may apply to a court of competent jurisdiction for temporary or preliminary injunctive relief on the ground that without such relief the arbitration provided in this paragraph may be rendered ineffectual. A Party may apply to any Federal or State court in Los Angeles County California to compel arbitration. Judgment upon the Award shall be entered by the District Court of Los Angeles County California, which court shall be invested with the authority to grant and enforce any interim or permanent relief or injunction awarded, notwithstanding any statutory provision providing for venue in some other Court.
                    7.5 Survival. This Mutual Arbitration Provision will survive any termination of your relationship with Poochie.
                    8. LITIGATION CLASS ACTION WAIVER. To the extent allowed by applicable law, separate and apart from the Mutual Arbitration Provision the Parties agree that any proceeding to litigate in court any dispute arising out of or relating to this Agreement, will be conducted solely on an individual basis, and User and Poochie agree not to seek to have any controversy, claim or dispute heard as a class action, a representative action, a collective action, a private attorney-general action, or in any proceeding in which User or Poochie acts or proposes to act in a representative capacity (“Litigation Class Action Waiver”). The Parties further agree that no proceeding will be joined, consolidated, or combined with another proceeding, without the prior written consent of all parties to any such proceeding.
                    9. MODIFICATIONS
                    9.1 Amendment This Agreement is the complete agreement of the Parties concerning the subject matter, and supersedes any prior agreements concerning the subject matter; and, may not be amended or in any manner modified except by a written instrument signed by authorized representatives of each and all Parties, except with respect to Poochie’s right to amend in section 1.4.
                    9.2 Exception. Poochie’s right to amend may be changed by Poochie according to section 1.4 and will bind the User once adopted without User signature upon User use of the Poochie Platform or Services following notice of the modification of the policy.
                    10. GOVERNING LAW AND LEGAL RECOURSE
                    10.1 California Law. This Agreement shall be construed and enforced in accordance with the federal law of the United States of America and the laws of the State of California, excluding its conflicts of law’s provisions.
                    10.2 Electronic Signatures. The provisions of The Ca. Uniform Electronic Transaction Act (UETA) Electronic Transactions Act and the Federal Electronic Signatures in Global and National Commerce Act (ESIGN) apply; and signatures and assent rendered under such acts shall be valid for all purposes.
                    10.3 Costs. Should either Party seek legal recourse to have the other Party comply with and/or fulfill any of its legal obligations under this Agreement, the prevailing Party shall be entitled to recover all reasonable attorney fees, expert fees and all costs incurred in connection therewith.
                    10.4 Courts. Actions seeking judicial relief may be brought only before federal or state courts having jurisdiction in Los Angeles County Court and each Party irrevocably submits to personal jurisdiction and waives any objection to venue in such courts. This provision does not negate mandatory arbitration.
                    11. NOTICE. Poochie may give notice by means of a general notice on the Services, electronic mail to your email address in your Account, telephone or text message to any phone number provided in connection with your account, or by written communication sent by first class mail or pre-paid post to any address connected with your Account. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email or telephone). You may give notice to Poochie, with such notice deemed given when received by Poochie, at any time by first class mail or pre-paid post to our registered agent for service of process, c/o XOX Rides Inc. 350 Salem st unit 201 Glendale Ca. 91203
                    12. MERGER, SEVERABILITY AND INTERPRETATION
                    12.1 Four Corners. The making, execution and delivery of this Agreement by the Parties hereto have been induced by no representations, statements, warranties or agreements other than those herein expressed. This Agreement embodies the entire understanding of the Parties hereto and there are no further or other agreements or understandings, written or oral, that govern this transaction.
                    12.2 Assignment. You may not assign this Agreement without Poochie’s prior written approval. Poochie may assign this Agreement without your consent to: (i) a subsidiary or affiliate; (ii) an acquirer of Poochie’s equity, business or assets; or (iii) a successor by merger. Any purported assignment in violation of this section shall be void. No joint venture, partnership, employment, or agency relationship exists between you, Poochie or Contractors as a result of this Agreement or use of the Services.
                    12.3 Severability. If any provision (or portion thereof) of this Agreement shall be declared invalid or unlawful, the remaining provisions shall not be affected thereby, and this Agreement shall be construed as if such invalid or unlawful provision (or portion thereof) had never been contained therein.
                    12.4 No Waiver. The failure of Poochie or User in any instance to insist upon a strict performance of the terms of this Agreement or to exercise any option herein, shall not be construed as a waiver or relinquishment of such term or option and such term or option shall continue in full force and effect. This provision shall not affect the Severability and Survivability section of the Arbitration Agreement of these Terms.
                    13. HEADINGS. Headings used throughout this Agreement are for administrative convenience only and shall be disregarded for the purpose of constructing and enforcing this Agreement.



                    https://doc-hosting.flycricket.io/poochie-terms-of-use/bf4d5e66-f753-48b9-b762-760b0bb6638f/terms


                </Text>

            </ScrollView>
        </View>
    )
}

export default PrivacyPolicy